import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service | Anteres AI',
  description: 'Terms of Service for Anteres AI content generation platform.',
};

export default function TermsOfService() {
  return (
    <main className="min-h-screen text-slate-200 px-6 py-16 md:px-12 selection:bg-indigo-500/30">
      <div className="max-w-3xl mx-auto">
        <Link href="/" className="text-sm text-slate-400 hover:text-white transition-colors mb-8 inline-block">
          ← Back to Dashboard
        </Link>

        <h1 className="text-3xl font-bold text-white mb-2">Terms of Service</h1>
        <p className="text-slate-500 text-sm mb-10">Last updated: April 11, 2025</p>

        <div className="space-y-8 text-slate-300 text-sm leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Anteres AI (&quot;the Service&quot;), you agree to be bound by these 
              Terms of Service. If you do not agree to these terms, please do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">2. Description of Service</h2>
            <p>
              Anteres AI is an AI-powered content intelligence platform that generates professional 
              content for social media and professional networks. The Service uses large language models 
              to create content based on user-provided inputs such as raw thoughts, news signals, 
              and domain context.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">3. User Accounts</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>You must create an account to access the Service.</li>
              <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
              <li>You are responsible for all activities that occur under your account.</li>
              <li>You must provide accurate and complete information when creating your account.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">4. Content Ownership</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong className="text-white">Your Inputs:</strong> You retain full ownership of all content you provide as input to the Service.</li>
              <li><strong className="text-white">Generated Content:</strong> Content generated by the AI engine is provided to you for your use. You are granted a perpetual, non-exclusive license to use, modify, and distribute generated content.</li>
              <li><strong className="text-white">Responsibility:</strong> You are solely responsible for reviewing, editing, and publishing any AI-generated content. You should verify facts and claims before publishing.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">5. Acceptable Use</h2>
            <p className="mb-3">You agree not to use the Service to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Generate content that is illegal, harmful, threatening, abusive, or defamatory.</li>
              <li>Impersonate any person or entity.</li>
              <li>Generate spam or misleading content at scale.</li>
              <li>Attempt to reverse-engineer, decompile, or disassemble the Service.</li>
              <li>Interfere with or disrupt the Service or servers.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">6. AI-Generated Content Disclaimer</h2>
            <p>
              Content generated by Anteres AI is produced by artificial intelligence models and may 
              contain inaccuracies, biases, or errors. The Service does not guarantee the accuracy, 
              completeness, or suitability of any generated content. Users should review and verify 
              all content before publishing or distributing it.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">7. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Anteres AI shall not be liable for any indirect, 
              incidental, special, consequential, or punitive damages arising from your use of the 
              Service, including but not limited to loss of profits, data, or business opportunities.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">8. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your access to the Service at any time, 
              with or without cause, and with or without notice. Upon termination, your right to 
              use the Service will immediately cease.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">9. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. We will notify users of any 
              material changes by updating the &quot;Last updated&quot; date. Continued use of the 
              Service after changes constitutes acceptance of the modified Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">10. Contact</h2>
            <p>
              For questions about these Terms, please contact us at{' '}
              <a href="mailto:rahulpandey1878@gmail.com" className="text-indigo-400 hover:text-indigo-300 transition-colors">
                rahulpandey1878@gmail.com
              </a>
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-slate-800 text-xs text-slate-600">
          <Link href="/privacy" className="text-indigo-400 hover:text-indigo-300 transition-colors">
            Privacy Policy →
          </Link>
        </div>
      </div>
    </main>
  );
}
